// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Currency")
                        .HasColumnType("numeric");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 15,
                            ProductName = "Mouse",
                            UnitPrice = 12.90m
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 200,
                            ProductName = "Keyboard",
                            UnitPrice = 169.90m
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 22,
                            ProductName = "Microfone",
                            UnitPrice = 34.90m
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 15,
                            ProductName = "HeadPhone",
                            UnitPrice = 115.90m
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 15,
                            ProductName = "Sound box",
                            UnitPrice = 12.90m
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 200,
                            ProductName = "Monitor",
                            UnitPrice = 169.90m
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 22,
                            ProductName = "Microphone Stand",
                            UnitPrice = 34.90m
                        },
                        new
                        {
                            Id = 8,
                            AvailableQuantity = 15,
                            ProductName = "Mug",
                            UnitPrice = 115.90m
                        },
                        new
                        {
                            Id = 9,
                            AvailableQuantity = 15,
                            ProductName = "Special Coffee",
                            UnitPrice = 12.90m
                        },
                        new
                        {
                            Id = 10,
                            AvailableQuantity = 200,
                            ProductName = "Webcam",
                            UnitPrice = 169.90m
                        },
                        new
                        {
                            Id = 11,
                            AvailableQuantity = 22,
                            ProductName = "MousePad",
                            UnitPrice = 34.90m
                        },
                        new
                        {
                            Id = 12,
                            AvailableQuantity = 15,
                            ProductName = "Computer Case",
                            UnitPrice = 115.90m
                        },
                        new
                        {
                            Id = 13,
                            AvailableQuantity = 15,
                            ProductName = "GPU",
                            UnitPrice = 12.90m
                        },
                        new
                        {
                            Id = 14,
                            AvailableQuantity = 200,
                            ProductName = "CPU",
                            UnitPrice = 169.90m
                        },
                        new
                        {
                            Id = 15,
                            AvailableQuantity = 22,
                            ProductName = "RAM memory",
                            UnitPrice = 34.90m
                        });
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.HasOne("Order", null)
                        .WithMany("Itens")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
